version: "3.7"
services:
  nginx:
    image: nginx:1.21.5
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
    depends_on:
      - django_gunicorn

  django_gunicorn:
    image: django-image:9
    networks:
      - network
    volumes:
      - static-volume:/home/ubuntu/nerdneck/static
      - media-volume:/home/ubuntu/nerdneck/media
    command: >
      bash -c "python manage.py migrate && gunicorn --env DJANGO_SETTINGS_MODULE=nerdneck.settings nerdneck.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout=60"

    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    networks:
      - network
    ports:
      - 6379:6379

networks:
  network:

volumes:
  static-volume:
  media-volume:
