version: "3.7"
services:
  nginx:
    image: nginx:1.21.5
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_gunicorn:
    image: django-image:3
    networks:
      - network
    volumes:
      - static-volume:/home/ubuntu/group-by-server/static
      - media-volume:/home/ubuntu/group-by-server/media
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    networks:
      - network
    ports:
      - 6379:6379

networks:
  network:

volumes:
  static-volume:
  media-volume: