# Generated by Django 3.2.7 on 2022-11-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('angles', models.JSONField(default=[])),
                ('average_angle', models.FloatField(default=0)),
                ('base_angle', models.FloatField(default=0)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
