# Generated by Django 3.2.7 on 2022-11-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurementapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
